apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: segundo-pod
spec:
  containers:
    - name: container-pod-2 # - inicio de uma nova declaracao
      image: nginx:latest
      ports:
        - containerPort: 80